CREATE TABLE IF NOT EXISTS `bdc_bid_document` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `app_key` varchar(64) NOT NULL COMMENT '业务系统appKey',
  `user_id` varchar(64) DEFAULT NULL COMMENT '发起预存的业务系统用户ID',
  `file_id` bigint NOT NULL COMMENT '文件服务fileId',
  `file_name` varchar(255) DEFAULT NULL COMMENT '原始文件名',
  `file_sha256` varchar(64) NOT NULL COMMENT '加密投标文件SHA-256',
  `file_storage_path` varchar(500) NOT NULL COMMENT 'crypto本地落盘路径',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小，单位字节',
  `upload_status` varchar(32) NOT NULL COMMENT '预存状态：PENDING/PROCESSING/SUCCESS/FAILED',
  `callback_status` varchar(32) DEFAULT NULL COMMENT '预存结果回调状态：PENDING/SUCCESS/FAILED',
  `callback_time` datetime DEFAULT NULL COMMENT '最近一次回调时间',
  `callback_error_message` text COMMENT '最近一次回调错误信息',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_id` bigint DEFAULT 0 COMMENT '创建人ID',
  `create_name` varchar(64) DEFAULT 'system' COMMENT '创建人名称',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_id` bigint DEFAULT 0 COMMENT '修改人ID',
  `modify_name` varchar(64) DEFAULT 'system' COMMENT '修改人名称',
  `ver` int DEFAULT 1 COMMENT '乐观锁版本号',
  `is_delete` tinyint DEFAULT 0 COMMENT '逻辑删除标识：0未删除 1已删除',
  PRIMARY KEY (`id`),
  KEY `idx_lookup` (`app_key`,`file_sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投标文件预存记录表';

CREATE TABLE IF NOT EXISTS `bdc_decrypt_artifact` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `app_key` varchar(64) NOT NULL COMMENT '业务系统appKey',
  `file_sha256` varchar(64) NOT NULL COMMENT '加密投标文件SHA-256',
  `bidder_pwd_fingerprint` varchar(64) NOT NULL COMMENT '投标口令指纹，用于解密结果去重',
  `status` varchar(32) NOT NULL COMMENT '工件状态：PENDING/PROCESSING/SUCCESS/FAILED',
  `retry_count` int DEFAULT 0 COMMENT '工件重试次数',
  `processing_started_at` datetime DEFAULT NULL COMMENT '本轮处理开始时间',
  `completed_at` datetime DEFAULT NULL COMMENT '工件完成时间',
  `error_message` text COMMENT '失败原因',
  `decrypt_result_json` longtext COMMENT '原始解密结果JSON',
  `decrypted_file_path` varchar(500) DEFAULT NULL COMMENT '解密后文件落盘路径',
  `decrypted_file_sha256` varchar(64) DEFAULT NULL COMMENT '解密后文件SHA-256',
  `bid_record_data_json` longtext COMMENT '提取后的标录JSON',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_id` bigint DEFAULT 0 COMMENT '创建人ID',
  `create_name` varchar(64) DEFAULT 'system' COMMENT '创建人名称',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_id` bigint DEFAULT 0 COMMENT '修改人ID',
  `modify_name` varchar(64) DEFAULT 'system' COMMENT '修改人名称',
  `ver` int DEFAULT 1 COMMENT '乐观锁版本号',
  `is_delete` tinyint DEFAULT 0 COMMENT '逻辑删除标识：0未删除 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_artifact_lookup` (`app_key`,`file_sha256`,`bidder_pwd_fingerprint`),
  KEY `idx_artifact_timeout` (`status`,`processing_started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='解密工件缓存表';

CREATE TABLE IF NOT EXISTS `bdc_decrypt_request` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID，同时作为recordId对外暴露',
  `artifact_id` bigint NOT NULL COMMENT '关联解密工件ID',
  `app_key` varchar(64) NOT NULL COMMENT '业务系统appKey',
  `project_id` varchar(64) NOT NULL COMMENT '项目ID',
  `tender_id` varchar(64) NOT NULL COMMENT '标段ID',
  `bid_record_id` varchar(64) NOT NULL COMMENT '开标标录ID',
  `file_sha256` varchar(64) NOT NULL COMMENT '加密投标文件SHA-256',
  `status` varchar(32) NOT NULL COMMENT '请求状态：PENDING/PROCESSING/SUCCESS/FAILED',
  `error_message` text COMMENT '失败原因',
  `callback_status` varchar(32) DEFAULT NULL COMMENT '解密结果回调状态：PENDING/SUCCESS/FAILED',
  `callback_retry_count` int DEFAULT 0 COMMENT '解密结果回调重试次数',
  `callback_response_code` varchar(32) DEFAULT NULL COMMENT '业务系统回调响应码',
  `callback_response_message` varchar(1000) DEFAULT NULL COMMENT '业务系统回调响应信息',
  `callback_time` datetime DEFAULT NULL COMMENT '最近一次回调时间',
  `requested_by_user_id` varchar(64) DEFAULT NULL COMMENT '提交解密请求的业务系统用户ID',
  `requested_by_user_name` varchar(100) DEFAULT NULL COMMENT '提交解密请求的业务系统用户名',
  `requested_by_enterprise_id` varchar(64) DEFAULT NULL COMMENT '提交解密请求的企业ID',
  `organized_encrypted_file_path` varchar(500) DEFAULT NULL COMMENT '按项目/标段组织的加密文件副本路径',
  `organized_decrypted_file_path` varchar(500) DEFAULT NULL COMMENT '按项目/标段组织的解密文件副本路径',
  `completed_at` datetime DEFAULT NULL COMMENT '请求完成时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_id` bigint DEFAULT 0 COMMENT '创建人ID',
  `create_name` varchar(64) DEFAULT 'system' COMMENT '创建人名称',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_id` bigint DEFAULT 0 COMMENT '修改人ID',
  `modify_name` varchar(64) DEFAULT 'system' COMMENT '修改人名称',
  `ver` int DEFAULT 1 COMMENT '乐观锁版本号',
  `is_delete` tinyint DEFAULT 0 COMMENT '逻辑删除标识：0未删除 1已删除',
  PRIMARY KEY (`id`),
  KEY `idx_request_bid_record` (`app_key`,`bid_record_id`),
  KEY `idx_request_artifact_id` (`artifact_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='解密请求记录表';
