openapi: 3.0.1
info: {}
paths:
  /api/file/esign/upload:
    summary: Esign 上传文件
    description: /api/file/esign/upload
    post:
      summary: Esign 上传文件
      description: /api/file/esign/upload
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 文件
  /api/file/upload:
    summary: 上传文件
    description: /api/file/upload
    post:
      summary: 上传文件
      description: /api/file/upload
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 文件
                bizType:
                  type: string
                  description: 业务类型
  /api/file/download/{fileId}:
    summary: 下载文件
    description: "/api/file/download/{fileId}"
    get:
      summary: 下载文件
      description: "/api/file/download/{fileId}"
      parameters: []
  /api/file/info/{fileId}:
    summary: 获取文件信息
    description: "/api/file/info/{fileId}"
    get:
      summary: 获取文件信息
      description: "/api/file/info/{fileId}"
      parameters: []
  /api/file/delete/{fileId}:
    summary: 删除文件
    description: "/api/file/delete/{fileId}"
    delete:
      summary: 删除文件
      description: "/api/file/delete/{fileId}"
      parameters: []
